### ISSUE TITLE
Deno error: `error: Uncaught ReferenceError: Static is not defined`

### ISSUE THREAD

**Issue by mindreframer** [sinclairzx81/typebox-codegen#18]
```ts
import * as Codegen from "npm:@sinclair/typebox-codegen";

const Code = Codegen.TypeScriptToTypeBox.Generate(`
  type T = { x: number, y: number, z: number }
  type C = { x: number, y: number, z: number }
  type D = { x: number, y: number, z: number }
`);

console.log(Code);

const model = Codegen.TypeScriptToModel.Generate(Code);
```

```bash
$ deno run -A codegen.ts

Unhandled: ImportDeclaration import { Type, Static } from '@sinclair/typebox'
Unhandled: TypeQuery typeof T
Unhandled: FirstStatement const T = Type.Object({
x: Type.Number(),
y: Type.Number(),
z: Type.Number()
})
Unhandled: TypeQuery typeof C
Unhandled: FirstStatement const C = Type.Object({
x: Type.Number(),
y: Type.Number(),
z: Type.Number()
})
Unhandled: TypeQuery typeof D
Unhandled: FirstStatement const D = Type.Object({
x: Type.Number(),
y: Type.Number(),
z: Type.Number()
})
error: Uncaught ReferenceError: Static is not defined
    at eval (eval at Exports (file:///Users/roman/Library/Caches/deno/npm/registry.npmjs.org/@sinclair/typebox-codegen/0.8.6/typescript/typescript-to-model.js:40:26), <anonymous>:6:1)
    at Exports (file:///Users/roman/Library/Caches/deno/npm/registry.npmjs.org/@sinclair/typebox-codegen/0.8.6/typescript/typescript-to-model.js:41:9)
    at Object.Generate (file:///Users/roman/Library/Caches/deno/npm/registry.npmjs.org/@sinclair/typebox-codegen/0.8.6/typescript/typescript-to-model.js:62:25)
    at file:///Users/roman/Desktop/EXPERIMENTS/0.DENO/astral/types/codegen.ts:9:41```

The errors seems to be triggered by this line: 

`https://github.com/sinclairzx81/typebox-codegen/blob/main/src/typescript/typescript-to-typebox.ts#L334`



On the positive side: 

`sinclairzx81/typebox` works _GREAT_ in Deno! Thanks, this is such a flexible library!

**Comment by sinclairzx81** [comment]
Just tested in Deno, this should work fine.

```typescript
import * as Codegen from "npm:@sinclair/typebox-codegen";

// Pass TypeScript Types to TypeScriptToTypeBox & TypeScriptToModel
const Code = `
  export type T = { x: number, y: number, z: number }
  export type C = { x: number, y: number, z: number }
  export type D = { x: number, y: number, z: number }
`

const Print = (output: string) => console.log(Codegen.Formatter.Format(output))

Print(Codegen.TypeScriptToTypeBox.Generate(Code))       // TypeBox

const model = Codegen.TypeScriptToModel.Generate(Code); // Model
Print(Codegen.ModelToValibot.Generate(model))           // Valibot
Print(Codegen.ModelToZod.Generate(model))               // Zod
                                                        // ... etc
```
Note the inputs to TypeScriptToTypeBox and TypeScriptToModel receive TS type code only. You may receive errors if passing any runtime constructs (i.e. functions, classes, variables or TypeBox types) as the code generation operates on TS static types only (so it's an error to pass generated TB code to TypeScriptToModel)

Hope this helps
S

**Comment by sinclairzx81** [comment]
@mindreframer Heya,

Might close off this issue for now as things are generally working as per current design. Currently the library is using a X to Y convention where the input representation for X should be constrained to X only (in this case TypeScript types expressed as strings) however the specific definitions for each representation of somewhat loose at the moment and not documented at all, I may address this in future.

```typescript
// unsupported - error: input is TB types, not TS types.
TypeScriptToModel.Generate(TypeScriptToTypeBox.Generate('type T = string'))

// supported
TypeScriptToModel.Generate('type T = string')

// future
const X = TypeScriptToTypeBox.Generate('type T = string')

const Y = TypeBoxToModel.Generate(X)

const Z = ModelToZod.Generate(Y)
```
All the best!
S

**Comment by mindreframer** [comment]
Thanks, that is helpful!
